#!/usr/bin/env bash
#This script listens on port 98 on localhost
# Listen on port 98 on localhost using nc
nc -l -p 98 -s localhost &

# Store the process ID for later termination
pid=$!

# Keep the script running indefinitely to maintain the connection
while true; do
  sleep 1
done

# Cleanup on script interruption (Ctrl+C)
trap 'kill $pid' SIGINT
